"""paired floor plans and review records"""

import sqlalchemy as sa
from alembic import op

revision = "0003_floor_plans"
down_revision = "0002_map_catalog"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("point_id", sa.String(length=36), nullable=False),
        sa.Column("map_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.CheckConstraint("status IN ('draft','published','retired')", name="ck_floors_status"),
        sa.CheckConstraint(
            "visibility IN ('public','internal','restricted')", name="ck_floors_visibility"
        ),
        sa.CheckConstraint("revision >= 1", name="ck_floors_revision"),
        sa.ForeignKeyConstraint(["map_id"], ["maps.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["point_id"], ["points.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("map_id", name="uq_floors_map"),
        sa.UniqueConstraint("point_id", "ordinal", name="uq_floors_point_ordinal"),
    )
    op.create_index("ix_floors_point", "floors", ["point_id", "status", "visibility"], unique=False)
    op.create_table(
        "floor_imports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("floor_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("reviewer", sa.String(length=120), nullable=False),
        sa.Column("rights_note", sa.Text(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["floor_id"], ["floors.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("floor_imports")
    op.drop_index("ix_floors_point", table_name="floors")
    op.drop_table("floors")
    # ### end Alembic commands ###
